Areas/Admin/Controllers/QuanLyQuyenController.cs
using LuxyryWatch.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LuxyryWatch.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuanLyQuyenController : AdminBaseController
    {
        // GET: Admin/QuanLyQuyen
        LuxuryWatch_DB db = new LuxuryWatch_DB();
        public ActionResult DanhSachQuyen(int? page, string search)
        {
            //Tạo biến số phần tử trên trang
            int pageSize = 5;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            var listQuyen = db.Quyens.ToList();
            if (search != null)
            {
                listQuyen = db.Quyens.Where(x => x.TenQuyen.Contains(search)).ToList();
                ViewBag.search = search;
            }
            return View(listQuyen.OrderBy(n => n.MaQuyen).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult ThemQuyen()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemQuyen(Quyen quyen)
        {
            if (ModelState.IsValid)
            {
                db.Quyens.Add(quyen);
                db.SaveChanges();
                return RedirectToAction("DanhSachQuyen");
            }
            ViewBag.ThongBao = "Có lỗi xảy ra!";
            return View();
        }
        public ActionResult SuaQuyen(String MaQuyen)
        {
            if (MaQuyen == null)
            {
                Response.StatusCode = 404;
            }
            var model = db.Quyens.SingleOrDefault(x => x.MaQuyen.Contains(MaQuyen));
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult SuaQuyen(Quyen quyen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quyen).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("DanhSachQuyen");
            }
            ViewBag.ThongBao = "Có lỗi xảy ra!";
            return View();
        }
        public ActionResult XoaQuyen(String MaQuyen)
        {
            if (MaQuyen == null)
            {
                Response.StatusCode = 404;
            }
            var model = db.Quyens.SingleOrDefault(x => x.MaQuyen.Contains(MaQuyen));
            if (model == null)
            {
                return HttpNotFound();
            }
            db.Quyens.Remove(model);
            db.SaveChanges();
            return Content("<script>window.location.reload();</script>");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                {
                    db.Dispose();
                }
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/QuanLyQuyen/DanhSachQuyen.cshtml
@using PagedList.Mvc
@using LuxyryWatch.Models
@model PagedList.IPagedList<Quyen>
@{
    ViewBag.Title = "SanhSachQuyen";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Quản lý quyền</h6>
    </div>
    <div class="col-md-4">
        <br />
        @using (Html.BeginForm("DanhSachQuyen", "QuanLyQuyen"))
        {
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" value="@ViewBag.search" name="search">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
                <a href="@Url.Action("ThemQuyen", "QuanLyQuyen")" type="submit" class="btn btn-success">Thêm mới</a>
            </form>
        }
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã quyền</th>
                        <th>Tên quyền</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.MaQuyen">
                            <td>@item.MaQuyen</td>
                            <td>@item.TenQuyen</td>
                            <td>
                                <a href="@Url.Action("SuaQuyen", "QuanLyQuyen", new { @MaQuyen = item.MaQuyen })">Sửa</a>
                                |
                                @Ajax.ActionLink("Xóa", "XoaQuyen", new { @MaQuyen = item.MaQuyen }, new AjaxOptions
                                {
                               Confirm = "Bạn có muốn xóa nhà cung cấp này?",
                               OnComplete = "$('#row_" + @item.MaQuyen + "').remove()",
                               OnSuccess = "location.reload()"
                           })
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <div>
            @Html.PagedListPager(Model, Page => Url.Action("DanhSachQuyen", new
       {
           page = Page,
           @search = @ViewBag.search
       }), new PagedListRenderOptions
       {
           LiElementClasses = new string[] { "item" },

       })
        </div>
    </div>

</div>
<style>
    .item {
        height: 30px;
        width: 30px;
        padding-top: 2px;
        border: 0.5px solid pink;
        text-align: center;
        border-radius: 3px;
    }

        .item a {
            color: black;
            text-decoration: none;
        }

    .pagination .active {
        background-color: #337AB7;
        color: white;
    }

    .item:hover {
        background-color: #EEEEEE;
    }
</style>



Areas/Admin/Views/QuanLyQuyen/SuaQuyen.cshtml
@model LuxyryWatch.Models.Quyen

@{
    ViewBag.Title = "SuaQuyen";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Cập nhật thông tin quyền: @Model.TenQuyen</h2>
<h3 style="color:red;">@ViewBag.ThongBao</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaQuyen)

        <div class="form-group">
            @Html.LabelFor(model => model.TenQuyen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenQuyen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenQuyen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "DanhSachQuyen")
</div>

Areas/Admin/Views/QuanLyQuyen/ThemQuyen.cshtml
@model LuxyryWatch.Models.Quyen

@{
    ViewBag.Title = "ThemQuyen";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}
<div class="card shadow mb-4">
    <div style="padding: 10px;">
        <h2>Tạo mới quyền</h2>
        <h3 style="color:red;">@ViewBag.ThongBao</h3>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.MaQuyen, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MaQuyen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaQuyen, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TenQuyen, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenQuyen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenQuyen, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Quay lại", "DanhSachQuyen")
        </div>
    </div>
</div>