Areas/Admin/Controllers/QuanLyLoaiThanhVienController.cs
using LuxyryWatch.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LuxyryWatch.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuanLyLoaiThanhVienController : AdminBaseController
    {
        LuxuryWatch_DB db = new LuxuryWatch_DB();
        // GET: Admin/Quanlyloaithanhvien
        public ActionResult DanhSachLoaiThanhVien(int? page, string search)
        {
            //Tạo biến số phần tử trên trang
            int pageSize = 5;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            var listLoaiThanhVien = db.LoaiThanhViens.ToList();
            if (search != null)
            {
                listLoaiThanhVien = db.LoaiThanhViens.Where(x => x.TenLoaiTV.Contains(search)).ToList();
                ViewBag.search = search;
            }
            return View(listLoaiThanhVien.OrderBy(n => n.MaLoaiTV).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult ThemLoaiThanhVien()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemLoaiThanhVien(LoaiThanhVien loaiThanhVien)
        {
            if (ModelState.IsValid)
            {
                db.LoaiThanhViens.Add(loaiThanhVien);
                db.SaveChanges();
                return RedirectToAction("DanhSachLoaiThanhVien");
            }
            ViewBag.ThongBao = "Có lỗi xảy ra!";
            return View();
        }
        public ActionResult SuaLoaiThanhVien(int? MaLoaiTV)
        {
            if (MaLoaiTV == null)
            {
                Response.StatusCode = 404;
            }
            var model = db.LoaiThanhViens.SingleOrDefault(x => x.MaLoaiTV == MaLoaiTV);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult SuaLoaiThanhVien(LoaiThanhVien loaiThanhVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loaiThanhVien).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("DanhSachLoaiThanhVien");
            }
            ViewBag.ThongBao = "Có lỗi xảy ra!";
            return View();
        }
        public ActionResult XoaLoaiThanhVien(int? MaLoaiTV)
        {
            if (MaLoaiTV == null)
            {
                return HttpNotFound();
            }

            var model = db.LoaiThanhViens.SingleOrDefault(x => x.MaLoaiTV == MaLoaiTV);
            if (model == null)
            {
                return HttpNotFound();
            }

            // Hiển thị trang xác nhận xóa
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult XoaLoaiThanhVien( LoaiThanhVien loaiThanhVien)
        {
            var model = db.LoaiThanhViens.Find(loaiThanhVien.MaLoaiTV);
            if (model == null)
            {
                return HttpNotFound();
            }

            try
            {
                db.LoaiThanhViens.Remove(model);
                db.SaveChanges();
                return RedirectToAction("DanhSachLoaiThanhVien");
            }
            catch (Exception ex)
            {
                ViewBag.ThongBao = "Đã xảy ra lỗi khi xóa: " + ex.Message;
                return View(model);
            }
        }
    }
}

Areas/Admin/Views/QuanLyLoaiThanhVien/DanhSachLoaiThanhVien.cshtml
@using PagedList.Mvc
@using LuxyryWatch.Models
@model PagedList.IPagedList<LoaiThanhVien>
@{
    ViewBag.Title = "DanhSachLoaiThanhVien";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Quản lý loại thành viên</h6>
    </div>
    <div class="col-md-4">
        <br />
        @using (Html.BeginForm("DanhSachLoaiThanhVien", "QuanLyLoaiThanhVien"))
        {
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" value="@ViewBag.search" name="search">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
                <a href="@Url.Action("ThemLoaiThanhVien", "QuanLyLoaiThanhVien")" type="submit" class="btn btn-success">Thêm mới</a>
            </form>

            @*<form>
                    <input type="text" class="form-control" value="@ViewBag.search" name="search" />
                    <input type="submit" class="btn btn-danger" value="Tìm kiếm" />
                    <a href="@Url.Action("ThemLoaiSanPham", "QuanLyLoaiSanPham")" type="submit" class="btn btn-success">Thêm mới</a>
                </form>*@
        }
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã loại thành viên</th>
                        <th>Tên loại thành viên</th>
                        <th>Ưu đãi</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.MaLoaiTV">
                            <td>@item.MaLoaiTV</td>
                            <td>@item.TenLoaiTV</td>
                            <td>@item.uuDai</td>
                            <td>
                                <a href="@Url.Action("SuaLoaiThanhVien", "QuanLyLoaiThanhVien", new { @MaLoaiTV = item.MaLoaiTV })">Sửa</a>
                                |
                                @Ajax.ActionLink("Xóa", "XoaLoaiThanhVien", new { @MaLoaiTV = item.MaLoaiTV }, new AjaxOptions
                                {
                               Confirm = "Bạn có muốn xóa bản ghi này?!",
                               OnComplete = "$('#row_" + @item.MaLoaiTV + "').remove()",
                               OnSuccess = "location.reload()"
                           })
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <div>
            @Html.PagedListPager(Model, Page => Url.Action("DanhSachLoaiThanhVien", new
       {
           page = Page,
           @search = @ViewBag.search
       }), new PagedListRenderOptions
       {
           LiElementClasses = new string[] { "item" },

       })
        </div>
    </div>

</div>
<style>
    .item {
        height: 30px;
        width: 30px;
        padding-top: 2px;
        border: 0.5px solid pink;
        text-align: center;
        border-radius: 3px;
    }

        .item a {
            color: black;
            text-decoration: none;
        }

    .pagination .active {
        background-color: #337AB7;
        color: white;
    }

    .item:hover {
        background-color: #EEEEEE;
    }
</style>



Areas/Admin/Views/QuanLyLoaiThanhVien/SuaLoaiThanhVien.cshtml
@model LuxyryWatch.Models.LoaiThanhVien

@{
    ViewBag.Title = "SuaLoaiThanhVien";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}
<div class="card shadow mb-4">
    <div style="padding: 10px;">
        <h2>Cập nhật thông tin loại thành viên : @Model.TenLoaiTV</h2>
        <h3 style="color:red;">@ViewBag.ThongBao</h3>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaLoaiTV)

                <div class="form-group">
                    @Html.LabelFor(model => model.TenLoaiTV, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenLoaiTV, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenLoaiTV, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.uuDai, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.uuDai, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.uuDai, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Quay lại", "DanhSachLoaiThanhVien")
        </div>
    </div>
</div>


Areas/Admin/Views/QuanLyLoaiThanhVien/ThemLoaiThanhVien.cshtml
@model LuxyryWatch.Models.LoaiThanhVien

@{
    ViewBag.Title = "ThemLoaiThanhVien";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}
<div class="card shadow mb-4">
    <div style="padding: 10px;">
        <h2>Tạo mới loại thành viên</h2>
        <h3 style="color:red;">@ViewBag.ThongBao</h3>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TenLoaiTV, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenLoaiTV, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenLoaiTV, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.uuDai, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.uuDai, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.uuDai, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Quay lại", "DanhSachLoaiThanhVien")
        </div>
    </div>
</div>


Areas/Admin/Views/QuanLyLoaiThanhVien/XoaLoaiThanhVien.cshtml
@model LuxyryWatch.Models.LoaiThanhVien

@{
    ViewBag.Title = "XoaLoaiThanhVien";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-body">
        <h2 class="card-title">Xác nhận xóa loại thành viên: @Model.TenLoaiTV </h2>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group row">
                    @Html.LabelFor(model => model.TenLoaiTV, "Tên Loại Thành Viên", htmlAttributes: new { @class = "col-md-2 col-form-label" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.TenLoaiTV, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.uuDai, "Ưu Đãi", htmlAttributes: new { @class = "col-md-2 col-form-label" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.uuDai, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                
                @Html.HiddenFor(model => model.TenLoaiTV)

                <div class="form-group row">
                    <div class="col-md-10 offset-md-2">
                        <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Hủy bỏ", "DanhSachLoaiThanhVien", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>
