Areas/Admin/Controllers/QuanLyNhaSanXuatController.cs
using LuxyryWatch.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Net;

namespace LuxyryWatch.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuanLyNhaSanXuatController : AdminBaseController
    {
        LuxuryWatch_DB db = new LuxuryWatch_DB();
        // GET: Admin/QuanLyNhaSanXuat
        public ActionResult DanhSachNhaSanXuat(int? page, string search)
        {
            //Tạo biến số phần tử trên trang
            int pageSize = 5;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            var listNhaSanXuat = db.NhaSanXuats.ToList();
            if (search != null)
            {
                listNhaSanXuat = db.NhaSanXuats.Where(x => x.TenNSX.Contains(search)).ToList();
                ViewBag.search = search;
            }
            return View(listNhaSanXuat.OrderBy(n => n.MaNSX).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult ThemNhaSanXuat()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemNhaSanXuat(NhaSanXuat nhaSanXuat)
        {
            if (ModelState.IsValid)
            {
                db.NhaSanXuats.Add(nhaSanXuat);
                db.SaveChanges();
                return RedirectToAction("DanhSachNhaSanXuat");
            }
            ViewBag.ThongBao = "Có lỗi xảy ra!";
            return View();
        }
        public ActionResult SuaNhaSanXuat(int? MaNSX)
        {
            if (MaNSX == null)
            {
                Response.StatusCode = 404;
            }
            var model = db.NhaSanXuats.SingleOrDefault(x => x.MaNSX == MaNSX);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult SuaNhaSanXuat(NhaSanXuat nhaSanXuat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhaSanXuat).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("DanhSachNhaSanXuat");
            }
            ViewBag.ThongBao = "Có lỗi xảy ra!";
            return View();
        }

        //public ActionResult XoaNhaSanXuat(int? MaNSX)
        //{
        //    if (MaNSX == null)
        //    {
        //        Response.StatusCode = 404;
        //    }
        //    var model = db.NhaSanXuats.SingleOrDefault(x => x.MaNSX == MaNSX);
        //    if (model == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    db.NhaSanXuats.Remove(model);
        //    db.SaveChanges();
        //    // Chuyển hướng trình duyệt đến cùng một trang
        //    return RedirectToAction("Index"); // Thay "Index" bằng tên Action của trang hiện tại
        //}

        public ActionResult XoaNhaSanXuat(int? MaNSX)
        {
            if (MaNSX == null)
            {
                return HttpNotFound();
            }

            var model = db.NhaSanXuats.SingleOrDefault(x => x.MaNSX == MaNSX);
            if (model == null)
            {
                return HttpNotFound();
            }

            // Hiển thị trang xác nhận xóa
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult XoaNhaSanXuat(NhaSanXuat nhaSanXuat)
        {
            var model = db.NhaSanXuats.Find(nhaSanXuat.MaNSX);
            if (model == null)
            {
                return HttpNotFound();
            }

            try
            {
                db.NhaSanXuats.Remove(model);
                db.SaveChanges();
                return RedirectToAction("DanhSachNhaSanXuat");
            }
            catch (Exception ex)
            {
                ViewBag.ThongBao = "Đã xảy ra lỗi khi xóa: " + ex.Message;
                return View(model);
            }
        }





        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                {
                    db.Dispose();
                }
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

Areas/Admin/Views/QuanLyNhaSanXuat/DanhSachNhaSanXuat.cshtml
@using PagedList.Mvc
@using LuxyryWatch.Models
@model PagedList.IPagedList<NhaSanXuat>
@{
    ViewBag.Title = "DanhSachNhaSanXuat";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Quản lý nhà sản xuất</h6>
    </div>
    <div class="col-md-4">
        <br />
        @using (Html.BeginForm("DanhSachNhaSanXuat", "QuanLyNhaSanXuat"))
        {
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" value="@ViewBag.search" name="search">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
                <a href="@Url.Action("ThemNhaSanXuat", "QuanLyNhaSanXuat")" type="submit" class="btn btn-success">Thêm mới</a>
            </form>

            @*<form>
                    <input type="text" class="form-control" value="@ViewBag.search" name="search" />
                    <input type="submit" class="btn btn-danger" value="Tìm kiếm" />
                    <a href="@Url.Action("ThemNhaSanXuat", "QuanLyNhaSanXuat")" type="submit" class="btn btn-success">Thêm mới</a>
                </form>*@
        }
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã nhà sản xuất</th>
                        <th>Tên nhà sản xuất</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.MaNSX">
                            <td>@item.MaNSX</td>
                            <td>@item.TenNSX</td>
                            <td>
                                <a href="@Url.Action("SuaNhaSanXuat", "QuanLyNhaSanXuat", new { @MaNSX = item.MaNSX })">Sửa</a>
                                |
                                @Ajax.ActionLink("Xóa", "XoaNhaSanXuat", new { @MaNSX = item.MaNSX }, new AjaxOptions
                                {
                               Confirm = "Bạn có muốn xóa bản ghi này?",
                               OnComplete = "$('#row_" + @item.MaNSX + "').remove()",
                               OnSuccess = "location.reload()"
                           })
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <div>
            @Html.PagedListPager(Model, Page => Url.Action("DanhSachNhaSanXuat", new
       {
           page = Page,
           @search = @ViewBag.search
       }), new PagedListRenderOptions
       {
           LiElementClasses = new string[] { "item" },

       })
        </div>
    </div>

</div>
<style>
    .item {
        height: 30px;
        width: 30px;
        padding-top: 2px;
        border: 0.5px solid pink;
        text-align: center;
        border-radius: 3px;
    }

        .item a {
            color: black;
            text-decoration: none;
        }

    .pagination .active {
        background-color: #337AB7;
        color: white;
    }

    .item:hover {
        background-color: #EEEEEE;
    }
</style>


Areas/Admin/Views/QuanLyNhaSanXuat/SuaNhaSanXuat.cshtml
@model LuxyryWatch.Models.NhaSanXuat

@{
    ViewBag.Title = "SuaNhaSanXuat";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}
<div class="card shadow mb-4">
    <div style="padding: 10px;">
        <h2>Cập nhật thông tin nhà sản xuất: @Model.TenNSX </h2>
        <hr />
        <h2 style="color: red;">@ViewBag.ThongBao</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaNSX)

                <div class="form-group">
                    @Html.LabelFor(model => model.TenNSX, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenNSX, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenNSX, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Quay lại", "DanhSachNhaSanXuat")
        </div>
    </div>
</div>

Areas/Admin/Views/QuanLyNhaSanXuat/ThemNhaSanXuat.cshtml
@model LuxyryWatch.Models.NhaSanXuat

@{
    ViewBag.Title = "ThemNhaSanXuat";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<div class="card shadow mb-4">
    <div style="padding: 10px;">
        <h2>Tạo mới nhà sản xuất</h2>
        <hr />
        <h2 style="color: red;">@ViewBag.ThongBao</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TenNSX, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenNSX, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenNSX, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Quay lại", "DanhSachNhaSanXuat")
        </div>
    </div>



</div>

Areas/Admin/Views/QuanLyNhaSanXuat/XoaNhaSanXuat.cshtml
@model LuxyryWatch.Models.NhaSanXuat

@{
    ViewBag.Title = "XoaNhaSanXuat";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<div class="card shadow mb-4">
    <div style="padding: 20px;">
        <h2>Xác nhận xóa nhà sản xuất: @Model.TenNSX </h2>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group row">
                @Html.LabelFor(model => model.TenNSX, "Tên nhà sản xuất", htmlAttributes: new { @class = "col-sm-2 col-form-label font-weight-bold" })
                <div class="col-sm-10">
                    @Html.DisplayFor(model => model.TenNSX, new { htmlAttributes = new { @class = "form-control-plaintext" } })
                </div>
            </div>

            @Html.HiddenFor(model => model.MaNSX)

            <div class="form-group row">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-danger">Xác nhận xóa</button>
                    <a href="@Url.Action("DanhSachNhaSanXuat")" class="btn btn-secondary ml-2">Hủy bỏ</a>
                </div>
            </div>
        }
    </div>
</div>