Areas/Admin/Controllers/QuanLyKhachHangController.cs
using LuxyryWatch.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LuxyryWatch.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuanLyKhachHangController : AdminBaseController
    {
        LuxuryWatch_DB db = new LuxuryWatch_DB();

        // GET: Admin/QuanLyKhachHang/DanhSachKhachHang
        public ActionResult DanhSachKhachHang(int? page, string search)
        {
            // Thiết lập kích thước trang và số trang
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var listKhachHang = db.KhachHangs.ToList();

            // Tìm kiếm khách hàng nếu có
            if (!string.IsNullOrEmpty(search))
            {
                listKhachHang = db.KhachHangs.Where(x => x.TenKH.Contains(search)).ToList();
                ViewBag.search = search;
            }

            return View(listKhachHang.OrderBy(n => n.Makh).ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/QuanLyKhachHang/SuaKhachHang/5
        public ActionResult SuaKhachHang(int? Makh)
        {
            if (Makh == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = db.KhachHangs.SingleOrDefault(x => x.Makh == Makh);

            if (model == null)
            {
                return HttpNotFound();
            }

            ViewBag.MaTV = new SelectList(db.ThanhViens.OrderBy(n => n.MaTV), "MaTV", "Hoten");

            return View(model);
        }

        // POST: Admin/QuanLyKhachHang/SuaKhachHang/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaKhachHang(KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khachHang).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("DanhSachKhachHang");
            }

            ViewBag.ThongBao = "Có lỗi xảy ra!";
            return View(khachHang);
        }

        // GET: Admin/QuanLyKhachHang/XoaKhachHang/5
        public ActionResult XoaKhachHang(int? Makh)
        {
            if (Makh == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = db.KhachHangs.SingleOrDefault(x => x.Makh == Makh);

            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }

        // POST: Admin/QuanLyKhachHang/XoaKhachHang/5
        [HttpPost, ActionName("XoaKhachHang")]
        [ValidateAntiForgeryToken]
        public ActionResult XacNhanXoaKhachHang(int Makh)
        {
            var model = db.KhachHangs.Find(Makh);

            if (model == null)
            {
                return HttpNotFound();
            }

            try
            {
                db.KhachHangs.Remove(model);
                db.SaveChanges();

                return RedirectToAction("DanhSachKhachHang");
            }
            catch (Exception ex)
            {
                ViewBag.ThongBao = "Đã xảy ra lỗi khi xóa: " + ex.Message;

                return View(model);
            }
        }
    }
}

Areas/Admin/Views/QuanLyKhachHang/DanhSachKhachHang.cshtml
@using PagedList.Mvc
@using LuxyryWatch.Models
@model PagedList.IPagedList<KhachHang>
@{
    ViewBag.Title = "DanhSachKhachHang";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Quản lý khách hàng</h6> <!-- Thay đổi tiêu đề -->
    </div>
    <div class="col-md-4">
        <br />
        @using (Html.BeginForm("DanhSachKhachHang", "QuanLyKhachHang"))
        {
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" value="@ViewBag.search" name="search">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
        }
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã khách hàng</th>
                        <th>Họ và tên</th>
                        <th>Địa chỉ</th>
                        <th>Email</th>
                        <th>Số điện thoại</th>
                        <th>Tài khoản</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.Makh">
                            <td>@item.Makh</td>
                            <td>@item.TenKH</td>
                            <td>@item.DiaChi</td>
                            <td>@item.Email</td>
                            <td>@item.SoDienThoai</td>
                            @if (item.MaTV == null)
                            {
                                <td></td>
                            }
                            else
                            {
                                <td>@item.ThanhVien.TaiKhoan</td>
                            }

                            <td>
                                <a href="@Url.Action("SuaKhachHang", "QuanLyKhachHang", new { Makh = item.Makh })">Sửa</a>
                                |
                                @Ajax.ActionLink("Xóa", "XoaKhachHang", new { Makh = item.Makh }, new AjaxOptions
                                {
                                    Confirm = "Bạn có muốn xóa bản ghi này?!",
                                    OnComplete = "$('#row_" + @item.Makh + "').remove()",
                                    OnSuccess = "location.reload"
                                })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div>
            @Html.PagedListPager(Model, Page => Url.Action("DanhSachKhachHang", new { page = Page, search = ViewBag.search }), new PagedListRenderOptions { LiElementClasses = new string[] { "item" } })
        </div>
    </div>
</div>

<style>
    .item {
        height: 30px;
        width: 30px;
        padding-top: 2px;
        border: 0.5px solid pink;
        text-align: center;
        border-radius: 3px;
    }

        .item a {
            color: black;
            text-decoration: none;
        }

    .pagination .active {
        background-color: #337AB7;
        color: white;
    }

    .item:hover {
        background-color: #EEEEEE;
    }
</style>

Areas/Admin/Views/QuanLyKhachHang/SuaKhachHang.cshtml
@model LuxyryWatch.Models.KhachHang 

@{
    ViewBag.Title = "SuaKhachHang";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}
<div class="card shadow mb-4">
    <div style="padding: 10px;">
        <h2>Cập nhật thông tin khách hàng : @Model.TenKH</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Makh)

                <div class="form-group">
                    @Html.LabelFor(model => model.TenKH, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SoDienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaTV, "Thành viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("MaTV", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaTV, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Quay lại", "DanhSachKhachHang")
        </div>


Areas/Admin/Views/QuanLyKhachHang/XoaKhachHang.cshtml
@model LuxyryWatch.Models.KhachHang

@{
    ViewBag.Title = "XoaKhachHang";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-body">
        <h2 class="card-title">Xác nhận xóa khách hàng: @Model.TenKH </h2>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group row">
                    @Html.LabelFor(model => model.TenKH,"Tên Khách Hàng", htmlAttributes: new { @class = "col-md-2 col-form-label" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.DiaChi, "Địa Chỉ", htmlAttributes: new { @class = "col-md-2 col-form-label" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Email, "Email", htmlAttributes: new { @class = "col-md-2 col-form-label" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.SoDienThoai, "Số Điện Thoại", htmlAttributes: new { @class = "col-md-2 col-form-label" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.MaTV, "Mã Thành Viên", htmlAttributes: new { @class = "col-md-2 col-form-label" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.MaTV, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                @Html.HiddenFor(model => model.TenKH)

                <div class="form-group row">
                    <div class="col-md-10 offset-md-2">
                        <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Hủy bỏ", "DanhSachKhachHang", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>